### ISSUE TITLE
Table numbering issue for highlight

### ISSUE THREAD

**Issue by papersaltserver** [matsuyoshi30/harbor#106]
There is an issue with paddings when line numbers placed in table mode:
![image](https://user-images.githubusercontent.com/8975555/118193355-d4c09280-b447-11eb-9048-8538ad901258.png)

**Comment by papersaltserver** [comment]
Further investigation showed it is due 
```css
pre code {
    padding: 0;
    font-family: Menlo, Monaco, Consolas, monospace;
    font-size: inherit;
    color: inherit;
    **white-space: pre-wrap;**
    background-color: transparent;
    border-radius: 0;
}
```
