### ISSUE TITLE
Google Analytics Not Working

### ISSUE THREAD

**Issue by jakehell** [matsuyoshi30/harbor#21]
I set my tracking key using `googleAnalytics = "<key>"` in the `config.toml` file. 

However, there's no google analytics `<script>` in the generated `index.html`.

If I add this in `config.toml`:

```
[params]
	googleAnalytics = "<key>"
```

And change `analytics.html` to:
```html
{{ if not .Site.IsServer }}
  {{ with .Site.Params.googleAnalytics }}
<script async src="https://www.googletagmanager.com/gtag/js?id={{ . }}"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '{{ . }}');
  </script>
  {{ end }}
{{ end }}
```

The google analytics `<script`> is added correctly.

**Comment by matsuyoshi30** [comment]
Hi @jakehell!

Thank you for letting me know about that and PR! I really appreciate your help, but I want to know more details about that issue.

Could you show me your `config.toml` when doesn't generate google analytics script in the `index.html`?

**Comment by jakehell** [comment]
@matsuyoshi30 

https://github.com/jakehell/blog/blob/f9b9443baaf1d0e121052c91f73ce42154cd651c/config.toml

This is what it looked like.

**Comment by matsuyoshi30** [comment]
@jakehell 

Thank you for sharing, and I figured out what happens.
If you set top-level configuration like google analytics, you need to move your top-level options in config.toml to the beginning of the config file. 

ref: https://stackoverflow.com/questions/46162211/google-analytics-does-not-work-with-blogdown/46207854#46207854

```toml
theme = "harbor"

[markup.goldmark.renderer]
  unsafe = true

googleAnalytics = "XXXX"
```

You change `config.toml` like below.

```toml
theme = "harbor"
googleAnalytics = "XXXX"

[markup.goldmark.renderer]
  unsafe = true
```

Please try it! If you still have a problem, let me know.
